# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      llvm_version: 13.0.0
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Get CMake
        uses: lukka/get-cmake@latest
      
      - name: Checkout llvm
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          ref: "llvmorg-${{ env.llvm_version }}"
          path: 'llvm'
      

      # Runs a single command using the runners shell
      - name: Build llvm
        run: |
          mkdir build
          mkdir install
          cmake `
            -S ".\llvm\llvm" `
            -B ".\build" `
            -G "Visual Studio 16 2019" `
            -Thost=x64 `
            -A x64 `
            -DLLVM_ENABLE_PROJECTS="lld;clang" `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_INSTALL_PREFIX=".\install"
          cmake --build .\build --target INSTALL --config Release -j
          7z a -mx9 "LLVM-${{ env.llvm_version }}-win64.7z" ".\install\*"

      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: LLVM-${{ env.llvm_version }}-win64
          path: LLVM-${{ env.llvm_version }}-win64.7z
        

